name: ts2dart
description: Transpiles TypeScript declaration files (.d.ts) to Dart interop
version: 0.0.1-beta.2
repository: https://github.com/jodinathan/typings/ts2dart
funding: 
  - https://www.paypal.com/donate?hosted_button_id=YNCG33GLM3494

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

# Add regular dependencies here.
dependencies: 
  archive: ^3.3.6
  built_collection: ^5.1.1
  code_builder: ^4.4.0
  collection: ^1.17.1
  console: ^4.1.0
  dart_style: ^2.2.5
  http: ^0.13.5
  logging: ^1.1.1
  meta: ^1.9.0
  path: ^1.8.3
  recase: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.1
  build_web_compilers: ^4.0.0
  #build_daemon: ^4.0.0
  js: any

dependency_overrides:
  code_builder:
   git: https://github.com/jodinathan/code_builder
  # dart_style:
  #  git: https://github.com/dart-lang/dart_style
  # build_runner:
  #  path: ../../build/build_runner