name: ts2dart
description: Transpiles TypeScript declaration files (.d.ts) to Dart interop
version: 0.0.6+3
repository: https://github.com/jodinathan/typings/
funding: 
  - https://www.paypal.com/donate?hosted_button_id=YNCG33GLM3494

environment:
  sdk: '>=3.3.0 <4.0.0'

# Add regular dependencies here.
dependencies: 
  archive: ^4.0.2
  built_collection: ^5.1.1
  code_builder: ^4.10.1
  collection: ^1.18.0
  console: ^4.1.0
  dart_style: ^2.2.7
  glob: ^2.1.2
  http: ^1.2.2
  logging: ^1.3.0
  meta: ^1.16.0
  path: ^1.8.3
  recase: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.1
  build_web_compilers: ^4.0.0
  #build_daemon: ^4.0.0
  js: any

dependency_overrides:
  code_builder:
   git: https://github.com/jodinathan/code_builder
  # dart_style:
  #  git: https://github.com/dart-lang/dart_style
  # build_runner:
  #  path: ../../build/build_runner
