name: typings
description: Use NPM packages in your projects through TypeScript interop
version: 0.0.6+3
repository: https://github.com/jodinathan/typings/
funding: 
  - https://www.paypal.com/donate?hosted_button_id=YNCG33GLM3494

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  build: ^2.4.1
  js: ^0.7.1
  source_gen: ^1.5.0
  ts2dart: any
  analyzer: ">=6.7.0 <7.0.0" # added >= and <= signs to make it compatible in all flutter 3.24.3

dev_dependencies:
  build_web_compilers: ^4.0.11
  build_runner: ^2.4.13
  build_daemon: ^4.0.2
  lints: ^5.0.0
  test: ^1.25.8

dependency_overrides:
  ts2dart:
    path: ../ts2dart
  code_builder:
   git: https://github.com/jodinathan/code_builder
